### ISSUE TITLE
[BUG]: After setting a bad URL, unable to successfully open the app again.

### ISSUE THREAD

**Issue by futurepr0n** [bbtufty/nxbrew-dl#41]
### Describe the Bug

Unable to re-open the app after setting a bad URL. I am unable to find the correct location to clear the config or cache in order to open the app as first time. Right now I am just getting an error anytime I go to open the app.

![Screenshot 2024-12-23 at 10 54 35 AM](https://github.com/user-attachments/assets/a96ead8e-cfc4-4708-8a26-02fa970fec47)

### Expected Behavior

I would expect the GUI to open, and allow me to reset the URL.

### Steps to reproduce the behavior

1. Set URL to nxbrew.com
2. Close app
3. Re-open app
4. watch app crash
...

### Preference File

```yaml
![Screenshot 2024-12-23 at 10 54 35 AM](https://github.com/user-attachments/assets/a96ead8e-cfc4-4708-8a26-02fa970fec47)
```

### Log

`>nxbrew_dl.exe
[2024-12-23 10:54:25] WARNING: Do not close this window!
[2024-12-23 10:54:25] INFO: Checking for new versions online
[2024-12-23 10:54:25] INFO: You have the latest version of NXBrew-dl
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 730, in connect
  File "urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 455, in wrap_socket
  File "ssl.py", line 1041, in _create
  File "ssl.py", line 1319, in do_handshake
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nxbrew.com', port=443): Max retries exceeded with url: /Index/game-index/games/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nxbrew_dl_gui.py", line 4, in <module>
  File "nxbrew_dl\__init__.py", line 12, in run_nxbrew_gui
  File "nxbrew_dl\gui\gui_nxbrew_dl.py", line 175, in __init__
  File "nxbrew_dl\gui\gui_nxbrew_dl.py", line 242, in load_table
  File "nxbrew_dl\gui\gui_nxbrew_dl.py", line 212, in get_game_dict
  File "nxbrew_dl\util\html_tools.py", line 58, in get_game_dict
  File "nxbrew_dl\util\html_tools.py", line 24, in get_html_page
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 698, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='nxbrew.com', port=443): Max retries exceeded with url: /Index/game-index/games/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[PYI-2708:ERROR] Failed to execute script 'nxbrew_dl_gui' due to unhandled exception!`

**Comment by bbtufty** [comment]
Fixed in #42. I've also just pushed a new version so you should be able to grab the latest .exe
